### ISSUE TITLE
GND-Connection between ESP and Mara?

### ISSUE THREAD

**Issue by ShuzzDE** [alexrus/marax_timer#16]
Hi!
I'm wondering how the serial communication is supposed to work since there doesn't seem to be any GND connection between the MCU and the coffee machine?
Looking at code and documentation, only the RX and TX lines seem to be connected - no GND.

I'd like to understand how this is supposed to work before trying to build it.

Best regards!

**Comment by alexrus** [comment]
Well, I can't explain, but I think you can connect the ground as well, if you know what is the GND pin on the MaraX

**Comment by ShuzzDE** [comment]
I've been trying to find out what the GND pin is, but no luck so far... ;-)
You don't happen to know that, do you? ;-)

My guess is that it works because the communication is only half-duplex. But it still is just sheer luck.

**Comment by alexrus** [comment]
Yeah, I have no idea what the GND pin is

**Comment by bancbanus** [comment]
Hi ShuzzDE,

I'm also wondering what type of connection it is. Watching LelitInsider's video I've seen that he is connecting a 4-wire-cable, so it looks like a standard full duplex serial connection (see https://youtu.be/9NL6yeq7sMM )

In all projects on github pin 3 is assumed as RX and pin 4 as TX (see https://github.com/bancbanus/marax_monitor/blob/main/hardware/marax_control_box.png). I've seen that Alexrus is sending data to the RX pin, but in my tests this doesn't have any effect. Maybe pin 3 is the GND pin?

You said that you were trying to find out the GND pin? Can you tell me how you did it? Did you use the multimeter? A logic analyzer or an oscilloscope?

I didn't want to brick the coffee machine (and upset my wife), that's why I didn't do any further investigations. I would be pleased if you can share your insights :-)

I would also like to know if there is a Vout pin which can be used to power the ESP32. Maybe the first pin? Because all V+ pins are labelled as squares on the control box' schematic.

Best regards!

**Comment by alexrus** [comment]
Actually I think it should be easy to find out.

MaraX has a 6 pin connector, we are using pins 3&4 for RX or TX (but not sure if 3 is RX or TX, depends if you start left to right or right to left)


The standard pinout is 5V, GND, RX, TX, RTS, CTS. So GND should be next to RX

**Comment by bancbanus** [comment]
Hi Alex,

thank you for your answer and yes, you're right :-)

The pinout (from the center to the edge) is most probably 5V, GND, RX, TX, RTS, CTS

BTW it has also been confirmed by larszi who realized a very impressive mod: https://github.com/larszi/marax-pressure-mod
