### ISSUE TITLE
Additional Hardware Information

### ISSUE THREAD

**Issue by mhellmeier** [alexrus/marax_timer#7]
It would be great if the README can be extended with detailed hardware information. 
Currently, the list contains the following information:
> Hardware:
> 
> * NodeMCU (ESP8266)
> * 0.96" oled display
> * reed sensor
> * wires
> * 3d printed case (https://www.thingiverse.com/thing:2937731)

These questions remain open:

1. Are there any preferred NodeMCU ESP8266 boards? Like CH340G, CP2102, CH9102X, ...
2. The linked 3D case is made for an SH1306 OLED display. Which is the correct one: the original, big one on the blue-colored board or the new smaller one on the black/dark-grey board?
3. Which reed sensor type is the correct one: open or closed?

**Comment by alexrus** [comment]
@mhellmeier 
1. I don't think there are prefered variants, as long as it has an esp8266 the code should work
2. the oled displayed used in the wiring diagram, is a diagram, that was the one I used to show the wiring. ofc, you need to use an oled display tha tis compatible with the 3d printed case. as long as it has i2c any oled display should work
3. I think it's normal open

**Comment by linesquarecube** [comment]
Very interesting project :) 
Do you know if it is possible to get 3.3V somewhere inside the MaraX? Since the power consumption of most ESP8266 based boards is very small, it would be very convenient to use it without an additional power adapter and just pick it somewhere. Especially if considering to use the very small ESP-01 board whith Wifi, the "extras" can stay inside the MaraX.

**Comment by alexrus** [comment]
I'm not sure, where you can get that power from.I did not search, because I didn't want to risk damaging the electronics of the machine.
