### ISSUE TITLE
lever direction reversed

### ISSUE THREAD

**Issue by clingergab** [alexrus/marax_timer#9]
Hey thanks for posting this. Everything worked fine until I connected pins 3 and 4 to the board. if i have it set up without them everything works great, the timer goes on and off perfectly. but when I connect pins 3 and 4 to D5 and D6 (or the other way around) this causes the machine to reverse the pump flow, so water comes out when the lever is lowered, and stops coming out when the lever is down. Any ideas why? Thanks!
edit: its the OPV discharge that water is coming out of not the water head.

**Comment by alexrus** [comment]
I have no idea why this would happen. pins 3&4 are data pins, so serial data is transmitted over them.
In the readme I mentioned to reverse them in case if does not work, because if you start counting from the left or right the order is the different one. Reversing them should not do this,  because there is no message sent to tell it to do so. My advice is to try with another nodeMCU board.

**Comment by clingergab** [comment]
Thanks for getting back to me. Yeah thats kinda wierd. I'll contact the lelit support and see if they have any info. on another note do you know if I should be able to connect to a 1.3" display with same number of pixels? or would I need to change anything in the code?

**Comment by alexrus** [comment]
you can connect any display that uses this driver: https://github.com/adafruit/Adafruit_SSD1306

If you have a non-compatible display, you probably need to use a different driver for it.
